Address cargo fmt and clippy issues
flatcar-linux/update-ssh-keys pull request #11
Opened 2023-10-19 15:57 UTC by dongsupark

Address issues of `cargo fmt` as well as `cargo clippy`.

In CI, run also `cargo fmt` and `cargo test`.
Use `actions-rs/cargo` Github Actions.

2023-10-19 16:03 UTC, dongsupark commented
(ignore the unit test failures, as it will be fixed in the other PR.)

2023-10-20 08:40 UTC, krnowak approved these changes

2023-10-20 09:41 UTC, pothos commented on .rustfmt.toml
> +fn_call_width=80
Is the reformat really worth it or can we rather go with the defaults to prevent git changes for all files?

2023-10-20 09:43 UTC, pothos commented on .rustfmt.toml
> +fn_call_width=80
`cargo fmt` shows no changes for me, do have a custom global config that causes the changes?

2023-10-20 09:44 UTC, pothos requested changes
Let's not use a custom `.rustfmt.toml` but stick to the existing (default rustfmt) formatting

2023-10-23 11:22 UTC, dongsupark commented on .rustfmt.toml
> +fn_call_width=80
Done with removing a local rustfmt.toml.

2023-10-23 11:23 UTC, dongsupark commented
Done with removing a local rustfmt.toml.

2023-10-23 12:34 UTC, krnowak approved these changes

2023-11-09 15:57 UTC, pothos approved these changes

2023-11-09 16:20 UTC, merged